### ISSUE TITLE
关于Evaluation部分的问题

### ISSUE THREAD

**Issue by sethzhangjs** [HITsz-TMG/Cognitive-Visual-Language-Mapper#2]
你好，我尝试根据Readme复现Evaluation的部分。
根据提示，我组织了checkpoint，unzip了图像。

但当我尝试执行bash命令的时候，会出现“huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/data/share/Model/opt-1.3b'. Use `repo_type` argument if needed.”的错误。

我不是很确定/data/share/Model/opt-1.3b是哪一部分。感谢您的帮助。
![Screenshot 2024-08-16 at 07 16 19](https://github.com/user-attachments/assets/49e11c07-3846-4930-b925-36da644d45ec)
![Screenshot 2024-08-16 at 07 16 35](https://github.com/user-attachments/assets/d8baa5ac-58e2-48b4-bba7-989db610185d)

**Comment by xyChen-HITSZ** [comment]
我们修改了代码使其现在能够正常从huggingface加载 facebook/opt-1.3b，当然，你也可以将LLaVA/llava/model/language_model/llava_llama.py中第36行的opt_model_path替换为你本地的opt-1.3b模型路径。

还有一点需要注意的是，我们提供的checkpoints中也有部分路径保留了训练时使用的绝对路径，你可能需要更新config.json和adapter_config.json文件
