### ISSUE TITLE
SAM image of InfoSeek

### ISSUE THREAD

**Issue by zui-jiang** [HITsz-TMG/Cognitive-Visual-Language-Mapper#3]
Thanks for your work, and is there a miss about sam images of infoseek datasets?
<img width="462" alt="image" src="https://github.com/user-attachments/assets/b89087d8-48a4-4373-92cf-fc014c0e44db">

**Comment by xyChen-HITSZ** [comment]
We apologize for the inconvenience. We have re-uploaded all the sam_images on [huggingface](https://huggingface.co/datasets/Ghaser/CVLM-SAM-Images). You will need to download them again.

**Comment by zui-jiang** [comment]
tkx
